---
label: Products
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: price
  type: number
  label: Price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: album
  type: image_gallery
  config: {}
  label: Album
- name: max_quantity
  type: number
  label: max quantity
  description: The max amount a customer will be able to order of each item.
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: grams
  type: number
  label: grams
  description: the weight of the item in grams (used to calculate shipping)
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: out_of_stock
  type: boolean
  description: toggle to display out of stock
  default: false
  label: Out of Stock
pages:
- src/products/Amethyst_Point.md
- src/products/Calcite_Kit.md
- src/products/Citrine.md
- src/products/Cleansing_Kit.md
- src/products/Crystal_Starter_Kit.md
- src/products/Honeycomb_Calcite.md
- src/products/Labradorite.md
- src/products/Lavender_Smudge.md
- src/products/Marra-Mamba.md
- src/products/New Year Crystal Kit.md
- src/products/Orange_Selenite.md
- src/products/Rose_Quartz.md
- src/products/Selenite.md
- src/products/Selenite_Bowl.md
- src/products/Smoky_Quartz.md
- src/products/White_Sage_Smudge.md
