name: GitHub Artifacts - Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  Branches: master
  MainBranch: master
  NPMRegistry: https://registry.npmjs.org/
  InstallCommand: npm ci
  BuildCommand: npm run build
  Output: ./_site
